image: gitpod/workspace-java-17

tasks:
  - init: |
      # Iniciar Docker Compose
      docker-compose up -d

      # Instalar e configurar Java 17
      sudo apt update && sudo apt install -y openjdk-17-jdk
      echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> ~/.bashrc
      echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> ~/.bashrc
      source ~/.bashrc

      # Verificar versão do Java
      java -version

  - command: |
      # Esperar MySQL iniciar completamente
      while ! docker exec mysql mysqladmin ping --host=127.0.0.1 --silent -uroot -prootpass; do
        sleep 2
      done


      # Mostrar os bancos disponíveis para verificar se foi criado corretamente
      mysql -u root -prootpass -e "SHOW DATABASES;"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - humao.rest-client
    - vscjava.vscode-gradle

ports:
  - port: 8080
    visibility: public
