image: gitpod/workspace-mysql

tasks:
  - init: |
    #Iniciar Doker Compose
    docker-compose up -d

    #Garantir que o mysql esteja rodando antes de ser criado
    while ! mysqladmin ping --host=127.0.0.1 --silent; do
      sleep 2
    done

    #Criar banco d dados se não existir
    mysql -u -e "CREATE DATABASE IF NOT EXISTS applicationbd"

    # Instalar e configurar Java 17
    sudo apt update && sudo apt install -y openjdk-17-jdk
    echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> ~/.bashrc
    echo "export PATH=\$JAVA_HOME/bin:\PATH" >> ~/.bashrc
    source ~/.bashrc


vscode:
    extensions:
      - vscjava.vscode-java-pack
      - humao.rest-client
      - vscjava.vscode-gradle

ports:
  - port: 8080
    visibility: public