image: gitpod/workspace-java-17

tasks:
  - init: |
      # Iniciar Docker Compose
      docker-compose up -d

      # Garantir que o MySQL esteja rodando antes de criar o banco
      while ! mysqladmin ping --host=127.0.0.1 --silent; do
        sleep 2
      done

      # Criar banco de dados se não existir
      mysql -u root -prootpass -e "CREATE DATABASE IF NOT EXISTS applicationdb"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - humao.rest-client
    - vscjava.vscode-gradle

ports:
  - port: 8080
    visibility: public
