version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: applicationdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppasswd
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sq
 